### PR TITLE
handle ExitError better, fix wofi link

### PR DESCRIPTION
**Pull request by mvdan**
(see commit messages - please do not squash)

### CODE REVIEW

**Comment by kenshaw** [comment]
@mvdan hey, been a while. How'd you even find this? rofimoji stopped working on me, so I hacked this together quickly. I was not really expecting anyone to use it/find it ... let me know if you're planning on submitting more commits or not.

**Comment by kenshaw** [comment]
@mvdan hey, been a while. How'd you even find this? rofimoji stopped working on me, so I hacked this together quickly. I was not really expecting anyone to use it/find it ... let me know if you're planning on submitting more commits or not.

**Comment by mvdan** [comment]
Hey! I found it via github's feed, I honestly didn't even know about rofimoji. It seems to support wofi as well, apparently. I'm not fussed about using either if you prefer not to receive PRs, though I do dislike having to deal with Python :)

**Comment by kenshaw** [comment]
@mvdan feel free to submit any PRs you want. I'll merge. not a problem for me. I was planning on making an "actual release" but have too many other development projects to contend with. Let me know when it's ready to merge.

**Comment by mvdan** [comment]
The PR is ready. I don't think I have any more changes to send for now, it just works.

**Pull request merged**
